# frozen_string_literal: true

require "securerandom"

# Decides WHETHER a leg overlay gets written to disk, and WHAT bytes it would
# contain, then (if the decision is "yes") performs exactly one atomic write.
#
# This is the first component in the whole uber-combat project that touches
# the user's own profiles directory and, via uc-leg.lic's "go" mode, starts a
# live hunt off what it wrote. Every rule below exists because getting it
# wrong here is not a bad diagnostic line -- it is a destroyed hand-written
# file, a half-written file a running script reads mid-write, or a hunt
# launched with an empty weapon_training that hands combat-trainer nothing to
# fight with.
#
# Almost pure: the only Lich/game dependency this file has at all is implicit
# -- overlay.settings#to_yaml is plain Ruby, and every filesystem call here is
# stdlib File. This class never touches $setupfiles, XMLData, or any other
# Lich global; the caller (uc-leg.lic) is the one Lich-aware layer, exactly as
# LegOverlay's own header describes itself as pure and pushes every
# Lich-facing read up to its caller (uc_leg_overlay.rb:10-14, uc_leg_settings.rb).
#
# path is always the ONE absolute path uc-leg.lic already derives through
# $setupfiles' own resolution (report_target_path, uc-leg.lic:148-160,
# contract Q9) -- this class neither hardcodes a directory nor accepts a path
# built from user input (uc-leg.lic's argument is a leg NUMBER, never a path
# string). That is the caller's obligation, not this class's; this class's
# obligation is to never write to whatever path it is given without first
# passing the two checks below.
module UberCombat
  class LegWriter
    # The first line of every file this class ever writes. Read back on the
    # next write attempt (see .decide) to tell "a file we generated, safe to
    # overwrite" from "a file a person wrote by hand, must never be touched."
    # Without this marker there is no way to tell those two cases apart from
    # the file's content alone, and the wrong guess in either direction is
    # destructive: overwrite a hand file and the user's edits are gone with
    # no undo; refuse to overwrite our own file and the leg overlay never
    # advances past whatever leg 1 happened to generate first.
    MARKER = "# GENERATED by uc-leg -- do not edit, it is overwritten on every leg change.\n"

    # A Struct, not a bare boolean, per the Overlay precedent
    # (uc_leg_overlay.rb:33-35, "so the gap report cannot be dropped by a
    # caller who destructures only what they expect"). `written` is false for
    # both refusal cases AND could in principle be false for other reasons
    # later; `reason` names which one so the caller never has to guess from a
    # bare false. reason is nil on success.
    Result = Struct.new(:written, :path, :reason, keyword_init: true)

    # decide's return value. `write` is the only field the orchestration
    # method (.write) branches on; `content` is nil for a refusal (there is
    # nothing to write) and the full file bytes, marker included, when
    # write is true; `reason` mirrors Result's field of the same name so a
    # refusal can be turned straight into a Result without translation.
    Decision = Struct.new(:write, :content, :reason, keyword_init: true)

    # overlay: an Overlay(settings:, gaps:), exactly LegOverlay#build's return
    #   value for ONE leg (uc_leg_overlay.rb:34, :91-129).
    # path: the absolute target file path. Always caller-derived (see the
    #   file header comment above) -- never validated or re-derived here,
    #   because this class has no way to know the correct profiles directory
    #   and must not guess at one.
    #
    # Reads the target file's first line (one filesystem read, if the file
    # exists at all), asks the pure .decide method what to do with that
    # information, and performs the one destructive filesystem call
    # (.write_atomically) if and only if .decide said to. Returns a Result on
    # every path -- refusal is a first-class outcome the caller prints, never
    # an exception the caller must rescue (an actual I/O failure inside
    # .write_atomically, e.g. a read-only directory, still raises -- that is
    # a real error, not a policy refusal, and the caller decides how to
    # surface it).
    def self.write(overlay, path)
      decision = decide(overlay, read_first_line(path))
      write_atomically(path, decision.content) if decision.write

      Result.new(written: decision.write, path: path, reason: decision.reason)
    end

    # PURE. No filesystem access of any kind -- this is the method the brief
    # asks for: the whole "whether to write, and what bytes" decision,
    # testable with nothing but a fabricated Overlay and a String or nil.
    #
    # existing_first_line: the target file's first line if the file exists
    #   (String, including its trailing newline exactly as File#gets returns
    #   it), or nil if the file does not exist at all. An existing-but-empty
    #   file reads back as "" from .read_first_line, which is neither nil nor
    #   MARKER, so it correctly falls into the foreign-file refusal below --
    #   an empty file is not one this class generated either.
    #
    # Order is deliberate: gaps are checked BEFORE the foreign-file check. A
    # leg with gaps is refused for the gap, never misreported as a
    # foreign-file conflict on the rare occasion both are simultaneously
    # true (a hand-written file already sits at the target AND the leg has a
    # gap) -- the gap is the reason a human actually needs to see and fix.
    def self.decide(overlay, existing_first_line)
      # Rule 1: refuse ANY gap. Printing the gaps themselves is the caller's
      # job (LegOverlay already returns them on the Overlay this method was
      # handed); this class only refuses to proceed. An empty
      # weapon_training would hand combat-trainer no weapons at all
      # (uc_leg_overlay.rb:109-116's own comment on the parallel
      # offensive_spells hazard makes the same point about never emitting an
      # incomplete catalogue) -- gaps are exactly the signal that happened.
      return refuse(:gaps) if overlay.gaps.any?

      # Rule 2: refuse to clobber a file we did not generate. nil (no file
      # at the target path) and an exact match on MARKER are the only two
      # bytes-identical-to-"safe to overwrite" states; anything else --
      # including a file that starts with a DIFFERENT comment, a file with
      # no comment at all, or an empty file -- is foreign and must stop this
      # method from ever computing content for it.
      return refuse(:foreign_file) unless existing_first_line.nil? || existing_first_line == MARKER

      # settings.to_yaml is the exact serialisation uc-leg.lic's read-only
      # report already prints as "the exact YAML that leg's profile overlay
      # would contain" (uc-leg.lic:119-122) -- this is that same call, now
      # actually going to disk instead of to DRC.message. The marker is
      # prepended as a real first line of the file (not a YAML comment
      # embedded inside the dump), so a MARKER string read back by
      # .read_first_line on the NEXT write compares byte-for-byte against
      # what was written here.
      Decision.new(write: true, content: MARKER + overlay.settings.to_yaml, reason: nil)
    end

    # Returns the target file's first line, or nil if the file does not
    # exist. The only read this class performs before deciding; kept
    # separate from .decide so the decision logic above needs no filesystem
    # of its own to be tested.
    def self.read_first_line(path)
      return nil unless File.exist?(path)

      File.open(path, "r") { |f| f.gets }
    end
    private_class_method :read_first_line

    # The one clearly separated method that actually commits bytes to disk,
    # per the brief's own instruction to isolate it. Writes to a temporary
    # file IN THE SAME DIRECTORY as the target, then renames over the
    # target.
    #
    # Same directory, not /tmp, and it is load-bearing, not a style choice:
    # rename(2) is atomic only within a single filesystem (POSIX rename(2)
    # guarantees atomicity for same-filesystem renames; a cross-filesystem
    # "rename" from /tmp would have to fall back to copy+delete, which is
    # exactly the non-atomic sequence this method exists to avoid). Profiles
    # reload on mtime change on EVERY get_settings call, including calls
    # made by a script that is already mid-hunt (contract Q10,
    # notes/uber-combat/35-overlay-contract.md, setup_files.rb:234-265's
    # cache-by-mtime check) -- a partially written file at the target path is
    # therefore not a theoretical race, it is a file a running Lich process
    # can genuinely open and parse mid-write. The rename makes the target
    # path jump from "old complete content" straight to "new complete
    # content" with no state in between ever observable by another reader.
    #
    # The temp filename includes both the process id and a random suffix so
    # two concurrent writers (e.g. a human re-running ;uc-leg write while an
    # earlier invocation is still finishing) can never collide on the same
    # temp path.
    def self.write_atomically(path, content)
      dir = File.dirname(path)
      tmp_path = File.join(dir, ".#{File.basename(path)}.#{Process.pid}.#{SecureRandom.hex(4)}.tmp")

      File.write(tmp_path, content)
      File.rename(tmp_path, path)
    rescue StandardError
      # A failed write or rename must not leave a stray temp file sitting in
      # the user's profiles directory forever. The target itself is
      # untouched either way -- rename never partially applies -- so there is
      # nothing to clean up there, only the temp file.
      File.delete(tmp_path) if tmp_path && File.exist?(tmp_path)
      raise
    end
    private_class_method :write_atomically

    def self.refuse(reason)
      Decision.new(write: false, content: nil, reason: reason)
    end
    private_class_method :refuse
  end
end
